### ISSUE TITLE
Бекенд. Реализация обработчика на запрос домашней страницы.

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/domain-checker#5]
При запросе на главную страницу ("/") сервер должен отдавать frontend/src/index.html.

**Comment by kabachook** [comment]
Отдачей статик контента должен заниматься nginx или apache - это best practice и написано в самой документации express. Для удобства разработки такое будет возможно при закуске с `NODE_ENV=dev`

**Comment by nikmel2803** [comment]
У нас там всего-то три файла (html, js, css) на фронте. Стоит ли заморачиваться с другими серверами?

**Comment by kabachook** [comment]
Да, если упадет экспресс, то статика упадет тоже. К тому же отдачей статики nginx и apache занимаются намного лучше экспресса. Также это позволяет хостить файлы и логику на разных серверах
