### ISSUE TITLE
Бекенд. WebSocket соединение.

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/domain-checker#7]
Клиент подключается по пути "/ws" и сразу после подключения отсылает id, который получил при AJAX запросе.
При успешном подключении и сверке id сервер начинает высылать данные в виде простой строки, которая содержит доступную доменную зону для запрашиваемого имени (пример сообщения: "ru"). Когда все доступные доменные зоны будут отправлены, сервер должен завершать соединение с кодом 1000 (Normal Closure). При какой-либо ошибке на стороне сервера соединение должно завершаться с кодом 1011 (Internal Error). При какой-либо ошибке, которая произошла по вине клиента, соединение должно закрываться с кодом 1008 (Policy Violation).
[Описание статус-кодов](https://tools.ietf.org/html/rfc6455#section-7.4)
[Документация к websocket.close()](https://github.com/websockets/ws/blob/HEAD/doc/ws.md#websocketclosecode-reason)

**Comment by kabachook** [comment]
Поменяли на `/ws/:id`, где id - id из AJAX запроса.
